namespace Blis.Common
{
	public enum RestErrorType
	{
		SUCCESS = 200,
		UNKNOWN = 1000,
		PARAMETER_TYPE_MISMATCH,
		PARAMETER_MISSED,
		PARAMETER_VALIDATION_FAILED,
		SESSION_HEADER_REQUIRED,
		UNAVAILALBE_REQUEST,
		UNDER_MAINTENANCE,
		INVALID_VERSION,
		MALFORMED_SESSION = 1100,
		ABNORMAL_ACCESS,
		SESSION_EXPIRED,
		BAN_USER = 1116,
		PERMANENT_BAN_USER,
		PAYMENT_PURCHASE_CANCELED = 9102
	}
}